# docker run --rm -p 8080:8080 -e bootstrapServers="127.0.0.1:9092" -e kouncil.auth.active-provider="inmemory" consdata/kouncil:1.5

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kouncil-deployment
  labels:
    app: kafka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kouncil
        image: consdata/kouncil:1.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: kouncil.auth.active-provider
          value: "inmemory"
        - name: bootstrapServers
          value: "kafka-service:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: kouncil-service
  labels:
    app: kafka
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - port: 8080
      targetPort: 8080
