name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd pyback-app
        python -m pip install --upgrade pip
        python -m pip install tox==4.4.7 poetry==1.4.0
        poetry install

    - name: Run tests
      run: |
        cd pyback-app
        tox -e testenv

    - name: Run linter
      run: |
        cd pyback-app
        tox -e lint

    - name: Coverage Badge
      run: |
        cd pyback-app
        poetry run pytest tests --cov src
        poetry run coverage-badge -o "docs/coverage.svg" -f

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v13
      id: verify-changed-files
      with:
        files: pyback-app/docs/coverage.svg

    - name: Commit files
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add pyback-app/docs/coverage.svg
        git commit -m "Update pyback-app coverage.svg"

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.github_token }}
        branch: ${{ github.ref }}
