name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-clean-badge:
    runs-on: ubuntu-latest
    steps:
    - name: Clean coverage badge
      run: |
        curl -s https://github.com/DimasDMM/live-timing-strategy/blob/master/README.md > README.md.tmp
        grep -Eo '<img src="[^"]+"' README.md.tmp | grep camo | grep -Eo 'https[^"]+' | xargs -I {} curl -w "\n" -s -X PURGE {}

  test-pipeline:
    runs-on: ubuntu-latest
    needs: pre-clean-badge
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd lts-pipeline
        python -m pip install --upgrade pip
        python -m pip install tox==4.4.7 poetry==1.4.0
        poetry install

    - name: Run tests
      run: |
        cd lts-pipeline
        tox -e testenv

    - name: Run linter
      run: |
        cd lts-pipeline
        tox -e lint

    - name: Coverage Badge
      run: |
        cd lts-pipeline
        poetry run pytest tests --cov src
        poetry run coverage-badge -o "docs/coverage.svg" -f

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v13
      id: verify-changed-files
      with:
        files: lts-pipeline/docs/coverage.svg

    - name: Commit files
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add lts-pipeline/docs/coverage.svg
        git commit -m "ci: Update lts-pipeline coverage.svg"

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.github_token }}
        branch: ${{ github.ref }}

  test-api:
    runs-on: ubuntu-latest
    needs: pre-clean-badge
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd lts-api
        python -m pip install --upgrade pip
        python -m pip install tox==4.4.7 poetry==1.4.0
        poetry install

    - name: Run tests
      run: |
        cd lts-api
        tox -e testenv

    - name: Run linter
      run: |
        cd lts-api
        tox -e lint

    - name: Coverage Badge
      run: |
        cd lts-api
        poetry run pytest tests --cov src
        poetry run coverage-badge -o "docs/coverage.svg" -f

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v13
      id: verify-changed-files
      with:
        files: lts-api/docs/coverage.svg

    - name: Commit files
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add lts-api/docs/coverage.svg
        git commit -m "ci: Update lts-api coverage.svg"

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.github_token }}
        branch: ${{ github.ref }}

  post-clean-badge:
    runs-on: ubuntu-latest
    needs:
    - test-pipeline
    - test-api
    steps:
    - name: Clean coverage badge
      run: |
        curl -s https://github.com/DimasDMM/live-timing-strategy/blob/master/README.md > README.md.tmp
        grep -Eo '<img src="[^"]+"' README.md.tmp | grep camo | grep -Eo 'https[^"]+' | xargs -I {} curl -w "\n" -s -X PURGE {}
